### ISSUE TITLE
Error while computing grouping with the updated parallelization

### ISSUE THREAD

**Issue by orasanen** [bootphon/tdev2#1]
Hi,

I tried to run the new grouping eval with updated parallelization, and I get the following error: 

ython /home/rasaneno/tdev2/tdev2/eval.py /home/rasaneno/ZS2020_tmp/test_submission/2017/track2/mandarin_full_1.0e-04.txt mandarin /home/rasaneno/ZS2020_tmp/eval/
Reading gold
Reading discovered classes
Discovered Class file read

197 unique intervals found
Computing Boundary...
Computing Grouping...
Traceback (most recent call last):
  File "/home/rasaneno/tdev2/tdev2/eval.py", line 105, in <module>
    main()
  File "/home/rasaneno/tdev2/tdev2/eval.py", line 84, in main
    grouping = Grouping(disc, output, args.njobs)
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given

**Comment by jukaradayi** [comment]
Hi, 

I did a fresh install on my local computer and I can't seem to reproduce it.
Are you up to date on the last commit ? 
you can try reinstalling the package, doing (inside the package folder):

> pip install -e .

and if it still doesn't work, check in the tdev2/measures/grouping.py file if you have the same line as https://github.com/bootphon/tdev2/blob/master/tdev2/measures/grouping.py#L11  . It looks like your init if missing the number of jobs argument.

**Comment by orasanen** [comment]
I did a fresh install and the problem persists. The init line looks exactly the same as in the github version. I'm not sure what is going on.

**Comment by orasanen** [comment]
I wonder if there's some problem with zerospeech2020 tools and tdev2 separately installed in the same conda environment, and import loads some of the libraries from ZS2020 repo instead of the tdev2 repository?

**Comment by jukaradayi** [comment]
Ah yes you're right that might be it, the import is importing the tde from ZS2020 which doesn't have the njobs argument. 
You can create a new environment

`conda env create --file environment.yml`
`conda activate TDE`
`pip install -e .`

and it should work !

**Comment by orasanen** [comment]
Yeah, that fixed the problem. Thanks!
