### ISSUE TITLE
Problem with checking boundary conditions in disc.get_transcription()

### ISSUE THREAD

**Issue by korhanpolat** [bootphon/tdev2#2]
Hi, 

I think there is a mistake while getting the transcription for a discovered interval in `disc_reader.py` - `get_transcription()` function. 
If the discovered interval is shorter than returned gold interval, the `keep_first` condition returns `True` even if the discovered interval does not satisfy 50% or 30ms overlap.

I'll try to explain with an example.

let's say a discovered interval is `(disc_on, disc_off)` 
and the corresponding gold transcription from `gold_phn[fname].overlap(disc_on, disc_off)` is `[(gold_on, gold_off)]`  (for simplicity assume single interval is returned )

so if  `gold_on` < `disc_on` <  `disc_off` < `gold_off` , the `keep_first` condition may return `True` even if |`disc_off` - `disc_on`| is very short to cover 50% or 30ms.

it is because `check_boundary` function is called with `(gold_on, gold_off),  (disc_on, gold_off)` arguments. 

Correct me if I'm wrong but I think the solution is to change these lines as:

`       keep_first = check_boundary(
            (covered[0][0], covered[0][1]),
            (disc_on, disc_off))`

`       keep_last = check_boundary(
            (covered[-1][0], covered[-1][1]),
            (disc_on, disc_off))
`

Is this a bug or is there another reason behind it that I'm missing? 
Thanks for your time and effort

**Comment by jukaradayi** [comment]
Hi, 

The way the `get_transcription()` function was built is mainly based on the case where the discovered interval covers multiples phones. In this case, since `disc_off > gold_off`, we want to check if the first is discovered so `check_boundary()` is indeed called with `disc_on` and `gold_off` as arguments. 
What you are pointing is indeed right, there can be a configuration where the discovered interval is very short that can give the wrong answer. I'm adding this in `get_transcription()`, I'll close the issue when it is fixed. 
Thanks for pointing it out !

**Comment by korhanpolat** [comment]
Thanks for your reply.

I'm asking this for clarification.
So if I understood correctly, it should be `check_boundary( (gold_on, gold_off), (disc_on, disc_off) )` for every case right?

Because for the case `disc_off > gold_off`, the internals of `overlap()` function selects the minimum anyway:   `min(disc_off , gold_off)`.  
Therefore in that case it wont matter whether we call it with `disc_off` or `gold_off`. 

So changing it to  `check_boundary( (gold_on, gold_off), (disc_on, disc_off) )`  wont affect the intended cases.

**Comment by jukaradayi** [comment]
Yes, as you said the `overlap` function select the minimum anyway so making the change you wrote works perfectly. 
I added a test and fixed the issue in commit https://github.com/bootphon/tdev2/commit/1ba58d9132755c1ab325d2419c051194f5c7a4bc 
Thank you !
